name: raouamth/frontend-session16

services:
  frontend-app:
    image: raouamth/frontend-session16:latest  

    container_name: frontend-app
    ports:
      - '3007:80'
#     networks:
#       - frontend-app-networ
#         # Connect to the defined network

# # Define networks
# networks:
#   frontend-app-network:
#     driver: bridge  # Use bridge networking for container communication

# # Manual build command (for reference):
# # docker build -t assidiwassimdev/frontend-app:latest --build-arg API_URL=https://api.lebondeveloppeur.net/api .
