name: Deploying to Staging

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t raouamth/frontend-session16:latest .

      - name: Push Docker image
        run: docker push raouamth/frontend-session16:latest



  deploy:
    name: Deploy to Server
    needs: build_and_push
    runs-on: [self-hosted, devops]

    steps:
      - name: Deploy with Docker Compose
        run: |
          cd /home/raoua/devops-script/frontend
           docker compose pull frontend-app
           docker compose up -d frontend-app --force-recreate