name: Deploying to Staging

on:
  push:
    branches:
      - main

jobs:


  deploy:
    name: Deploy to Server
    runs-on: [self-hosted, devops]

    steps:

      - name: Pull latest images
        run: docker compose -f docker-compose.yml pull

      - name: Deploy with Docker Compose
        run: docker compose -f docker-compose.yml up -d